sudo:
services:
  -docker
  
before_install:
  - docker build -t jordan/react-test -f ./client/Dockerfile.dev ./client
  
script:
  - docker run -e CI=true jordan/react-test npm test
   
after_success:
  - docker build -t kolloy/multi-client ./client
  - docker build -t kolloy/multi-nginx ./nginx
  - docker build -t kolloy/multi-server ./server
  - docker build -t kolloy/multi-worker ./worker
#Log into the docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
#Push new images up to docker hub 
  - docker push kolloy/multi-client
  - docker push kolloy/multi-nginx
  - docker push kolloy/multi-server
  - docker push kolloy/multi-worker