sudo:
services:
  -docker
  
before_install:
  - docker build -t kolloy/react-test -f ./client/Dockerfile.dev ./client
  
script:
  - docker run -e CI=true kolloy/react-test npm test
   
after_success:
  - docker build -t kolloy/multi-client ./client
  - docker build -t kolloy/multi-nginx ./nginx
  - docker build -t kolloy/multi-server ./server
  - docker build -t kolloy/multi-worker ./worker
#Log into the docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
#Push new images up to docker hub 
  - docker push kolloy/multi-client
  - docker push kolloy/multi-nginx
  - docker push kolloy/multi-server
  - docker push kolloy/multi-worker
  
#AWS Connections
deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "multi-docker"
  env: "MultiDocker-env"
  bucket_name: "elasticbeanstalk-us-east-1-620524101278"
  bucket_path: "docker-multi"
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  on:
    branch: master