sudo:
services:
  -docker
  
before_install:
  - docker build -t jordan/react-test -f ./client/Dockerfile.dev ./client
  
script:
  - docker run -e CI=true jordan/react-test npm test
   
after_success:
  - docker build -t jordan/multi-client ./client
  - docker build -t jordan/multi-nginx ./nginx
  - docker build -t jordan/multi-server ./server
  - docker build -t jordan/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  
  - docker push jordan/multi-client
  - docker push jordan/multi-nginx
  - docker push jordan/multi-server
  - docker push jordan/multi-worker